GET http://localhost:5002/api/products

###
GET http://localhost:5002/api/products/1

###
POST http://localhost:5002/api/products
Content-Type: application/json

{
  "name": "APPLE",
  "price": 13000,
  "stock": 15
}

###
PUT  http://localhost:5002/api/products/4
Content-Type: application/json

{
    "name":"gdfg",
    "price": 30000,
    "stock":10
}

###
DELETE http://localhost:5002/api/products/3