GET http://localhost:5002/api/orders

###
POST http://localhost:5002/api/orders
Content-Type: application/json

{
  "products": [
    {
      "id": 1,
      "quantity": 15
    },
    {
      "id": 2,
      "quantity": 20
    }
  ]
}

###
GET http://localhost:5002/api/orders/1


###
DELETE http://localhost:5002/api/orders/3